### PR TITLE
Replace all instances of jrbourbeau with pycondor

### PR DESCRIPTION
**Pull request by GregoryAshton**
#### What does this pull request implement/fix? Explain your changes.

This PR implements a transition in the github namespace from jrbourbeau to pycondor.

### CODE REVIEW

**Comment by GregoryAshton** [comment]
@jodergrosse would you be able to review this and merge if you are happy?

**Comment by GregoryAshton** [comment]
I think actually, I'm going to just self-review here - the changes are very minor and programmatic.

**Comment by jodergrosse** [comment]
Would have been ready to do so later today.

**Comment by GregoryAshton** [comment]
@jodergrosse could you send me an email at "gregory.ashton@rhul.ac.uk". It would be good to chat about the path forward on development if we can.

Best,

Greg

**Pull request merged**
